stages:
  - build
  - deploy

build-job:
  stage: build
  image: node:18
  script:
    - echo "Build started"
    - npm install
    - npm run build

deploy-job:
  stage: deploy
  script:
   - echo "Deploy successful (placeholder)"
# trikcer
